"""start_shift_assignment

Revision ID: 3de253806a02
Revises: 89c7649ce8f2
Create Date: 2025-06-15 23:46:14.653025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de253806a02'
down_revision = '89c7649ce8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_assignment',
    sa.Column('shift_assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('shift_assignment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_assignment')
    # ### end Alembic commands ###
