"""covered_by_account

Revision ID: 5fd924470d33
Revises: e060ae0cdc78
Create Date: 2025-06-19 16:09:34.893907

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5fd924470d33"
down_revision = "e060ae0cdc78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coverage_request", schema=None) as batch_op:
        batch_op.add_column(sa.Column("covered_by_account_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "coverage_request_account_covered_by_account_id", "account", ["covered_by_account_id"], ["account_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coverage_request", schema=None) as batch_op:
        batch_op.drop_constraint("coverage_request_account_covered_by_account_id", type_="foreignkey")
        batch_op.drop_column("covered_by_account_id")

    # ### end Alembic commands ###
