"""shift_completed

Revision ID: 87f7b53d0b07
Revises: b349d0807f5d
Create Date: 2025-06-19 16:37:50.959898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f7b53d0b07'
down_revision = 'b349d0807f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_datetime_utc', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_column('completed_datetime_utc')

    # ### end Alembic commands ###
