"""begin_shifts

Revision ID: 89c7649ce8f2
Revises: efed613600d3
Create Date: 2025-06-15 23:28:24.453683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c7649ce8f2'
down_revision = 'efed613600d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
    sa.Column('shift_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('comments', sa.String(length=255), server_default='', nullable=False),
    sa.Column('eggs_collected', sa.Integer(), nullable=True),
    sa.Column('eggs_left_behind', sa.Integer(), nullable=True),
    sa.Column('assigned_to_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_table('coverage_request',
    sa.Column('coverage_request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.shift_id'], ),
    sa.PrimaryKeyConstraint('coverage_request_id'),
    sa.UniqueConstraint('shift_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coverage_request')
    op.drop_table('shift')
    # ### end Alembic commands ###
