"""ledger_to_account_fk

Revision ID: 96e10fc00ec4
Revises: c216d09c2464
Create Date: 2025-06-01 08:22:36.127543

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "96e10fc00ec4"
down_revision = "c216d09c2464"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ledger_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by_account_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_ledger_item_account_id_account", "account", ["created_by_account_id"], ["account_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ledger_item", schema=None) as batch_op:
        batch_op.drop_constraint("fk_ledger_item_account_id_account", type_="foreignkey")
        batch_op.drop_column("created_by_account_id")

    # ### end Alembic commands ###
