"""new_start

Revision ID: a5ab06dde01a
Revises: 
Create Date: 2025-06-01 20:41:46.007877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ab06dde01a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('first_name', sa.String(length=16), nullable=False),
    sa.Column('last_name', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=42), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('clearance', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ledger_item',
    sa.Column('ledger_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ledger_item_type', sa.Integer(), nullable=False),
    sa.Column('ledger_item_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_datetime_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('ledger_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_item')
    op.drop_table('account')
    # ### end Alembic commands ###
