"""coverage_request_created_datetime_utc

Revision ID: b349d0807f5d
Revises: 5fd924470d33
Create Date: 2025-06-19 16:29:09.308459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b349d0807f5d'
down_revision = '5fd924470d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coverage_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_datetime_utc', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('comments', sa.String(length=255), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coverage_request', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('created_datetime_utc')

    # ### end Alembic commands ###
