"""ledger

Revision ID: c216d09c2464
Revises: d6107d954730
Create Date: 2025-05-31 22:36:34.345686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c216d09c2464'
down_revision = 'd6107d954730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_item',
    sa.Column('ledger_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ledger_item_type', sa.Integer(), nullable=False),
    sa.Column('ledger_item_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_datetime_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ledger_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_item')
    # ### end Alembic commands ###
