"""completed_by

Revision ID: c5aed90884d7
Revises: 87f7b53d0b07
Create Date: 2025-06-20 22:45:13.483417

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c5aed90884d7"
down_revision = "87f7b53d0b07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shift", schema=None) as batch_op:
        batch_op.add_column(sa.Column("completed_by_account_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "account_shift_completed_by_account_id",
            "account",
            ["completed_by_account_id"],
            ["account_id"],
        )

    with op.batch_alter_table("shift_assignment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("comments", sa.String(length=255), server_default="", nullable=False))
        batch_op.add_column(sa.Column("seeking_permanent_replacement", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shift_assignment", schema=None) as batch_op:
        batch_op.drop_column("seeking_permanent_replacement")
        batch_op.drop_column("comments")

    with op.batch_alter_table("shift", schema=None) as batch_op:
        batch_op.drop_constraint("account_shift_completed_by_account_id", type_="foreignkey")
        batch_op.drop_column("completed_by_account_id")

    # ### end Alembic commands ###
