"""relate_shift_to_shift_assignment

Revision ID: e060ae0cdc78
Revises: 3de253806a02
Create Date: 2025-06-15 23:51:45.653260

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e060ae0cdc78"
down_revision = "3de253806a02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shift", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shift_assignment_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "shift_assignment_shift_assignment_id",
            "shift_assignment",
            ["shift_assignment_id"],
            ["shift_assignment_id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shift", schema=None) as batch_op:
        batch_op.drop_constraint("shift_assignment_shift_assignment_id", type_="foreignkey")
        batch_op.drop_column("shift_assignment_id")

    # ### end Alembic commands ###
