"""start

Revision ID: ec5a9dacf44d
Revises:
Create Date: 2025-05-25 21:52:20.429384

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec5a9dacf44d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=24), nullable=False),
        sa.Column("first_name", sa.String(length=16), nullable=False),
        sa.Column("last_name", sa.String(length=24), nullable=False),
        sa.Column("email", sa.String(length=42), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("clearance", sa.Integer(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account")
    # ### end Alembic commands ###
