"""one_name

Revision ID: efed613600d3
Revises: a5ab06dde01a
Create Date: 2025-06-05 22:40:35.381388

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "efed613600d3"
down_revision = "a5ab06dde01a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.alter_column(
            "first_name",
            new_column_name="name",
            type_=sa.String(length=32),
            existing_type=sa.String(16),
        )

        batch_op.drop_column("last_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_name", sa.VARCHAR(length=24), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("first_name", sa.VARCHAR(length=16), autoincrement=False, nullable=False))
        batch_op.drop_column("name")

    # ### end Alembic commands ###
